# Generated by Django 4.2.1 on 2023-05-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_urequesr'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='artist_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='urequesr',
            name='date',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
