# Generated by Django 4.2.1 on 2023-05-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
